[package]
name = "ens-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio       = { version = "1", features = ["rt-multi-thread", "macros"] }
axum        = "0.6"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
tower       = "0.4"
tracing     = "0.1"
tracing-subscriber = "0.3"
