apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-deployment
  namespace: ens-backend-demo
  labels:
    app: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
        - name: smtp
          image: zkfr/smtp:latest
          ports:
            - containerPort: 3000
              name: smtp-port
          env:
            - name: SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: ens-backend-demo-secrets
                  key: SMTP_INTERNAL_SERVER_HOST
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: ens-backend-demo-secrets
                  key: SMTP_INTERNAL_SERVER_PORT
            - name: SMTP_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: ens-backend-demo-secrets
                  key: SMTP_DOMAIN_NAME
            - name: SMTP_LOGIN_ID
              valueFrom:
                secretKeyRef:
                  name: ens-backend-demo-secrets
                  key: SMTP_LOGIN_ID
            - name: SMTP_LOGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ens-backend-demo-secrets
                  key: SMTP_LOGIN_PASSWORD
            - name: MESSAGE_ID_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: ens-backend-demo-secrets
                  key: SMTP_MESSAGE_ID_DOMAIN
            - name: JSON_LOGGER
              valueFrom:
                secretKeyRef:
                  name: ens-backend-demo-secrets
                  key: SMTP_JSON_LOGGER
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 90
            timeoutSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-service
  namespace: ens-backend-demo
  labels:
    app: smtp
spec:
  selector:
    app: smtp
  ports:
    - name: smtp-port
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
