apiVersion: v1
kind: ServiceAccount
metadata:
  name: imap-cronjob-sa
  namespace: ens-backend-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ens-backend-demo
  name: imap-deployment-restart-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: imap-deployment-restart-rolebinding
  namespace: ens-backend-demo
subjects:
  - kind: ServiceAccount
    name: imap-cronjob-sa
    namespace: ens-backend-demo
roleRef:
  kind: Role
  name: imap-deployment-restart-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: imap-deployment-restart-cronjob
  namespace: ens-backend-demo
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: imap-cronjob-sa
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 128Mi
              command:
                - /bin/sh
                - -c
                - |
                  kubectl rollout restart deployment imap-deployment --namespace ens-backend-demo
          restartPolicy: OnFailure
